stages:
  - build
  - upload

build:
  stage: build
  image: registry.gitlab.localdev.cc/infra/base-container/node:14-full
  tags:
    - docker
  before_script:
    - npm i
    - npm run checkVulnerabilities
  script:
    - STAGE=development npm run build
    - STAGE=production npm run build
  artifacts:
    paths:
      - dist

.upload:
  stage: upload
  image: $CI_REGISTRY/sga/buildhelper/build-docker:latest
  tags:
    - docker
  only:
    - tags
  dependencies:
    - build
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_DEV
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_DEV
    AWS_S3_BUCKET: $AWS_S3_BUCKET_DEV
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_DEV

upload dev:
  extends: .upload
  script:
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni-enablement/${CI_COMMIT_TAG:1}/retailred-storefront-library-v2.js --body dist/dev/retailred-storefront-library-v2.js --content-type application/javascript --acl public-read
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni-enablement/${CI_COMMIT_TAG:1}/retailred-storefront-library-v2.css --body dist/dev/retailred-storefront-library-v2.css --content-type text/css --acl public-read
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni-enablement/${CI_COMMIT_TAG:1}/index.html --body dist/dev/index.html --content-type "text/html; charset=utf-8" --acl public-read
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni-enablement/${CI_COMMIT_TAG:1}/quick.html --body dist/dev/quick.html --content-type "text/html; charset=utf-8" --acl public-read
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni-enablement/${CI_COMMIT_TAG:1}/flags.png --body dist/dev/flags.png --content-type image/png --acl public-read
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni-enablement/${CI_COMMIT_TAG:1}/flags@2x.png --body dist/dev/flags@2x.png --content-type image/png --acl public-read
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni-enablement/${CI_COMMIT_TAG:1}/utils.js --body dist/dev/utils.js --content-type application/javascript --acl public-read
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni-enablement/latest/retailred-storefront-library-v2.js --body dist/dev/retailred-storefront-library-v2.js --content-type application/javascript --acl public-read
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni-enablement/latest/retailred-storefront-library-v2.css --body dist/dev/retailred-storefront-library-v2.css --content-type  text/css --acl public-read
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni-enablement/latest/index.html --body dist/dev/index.html --content-type "text/html; charset=utf-8" --acl public-read
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni-enablement/latest/quick.html --body dist/dev/quick.html --content-type "text/html; charset=utf-8" --acl public-read
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni-enablement/latest/flags.png --body dist/dev/flags.png --content-type image/png --acl public-read
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni-enablement/latest/flags@2x.png --body dist/dev/flags@2x.png --content-type image/png --acl public-read
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni-enablement/latest/utils.js --body dist/dev/utils.js --content-type application/javascript --acl public-read

upload prod:
  extends: .upload
  when: manual
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_LIVE
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_LIVE
    AWS_S3_BUCKET: $AWS_S3_BUCKET_LIVE
  script:
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni/retailred-storefront-library-${CI_COMMIT_TAG:1}.js --body dist/prod/retailred-storefront-library-v2.js --content-type application/javascript
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni/retailred-storefront-library-${CI_COMMIT_TAG:1}.css --body dist/prod/retailred-storefront-library-v2.css --content-type text/css
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni/retailred-storefront-library-v2.js --body dist/prod/retailred-storefront-library-v2.js --content-type application/javascript
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni/retailred-storefront-library-v2.css --body dist/prod/retailred-storefront-library-v2.css --content-type text/css
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni/flags.png --body dist/prod/flags.png --content-type image/png
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni/flags@2x.png --body dist/prod/flags@2x.png --content-type image/png
    - aws s3api put-object --bucket $AWS_S3_BUCKET --key omni/utils.js --body dist/prod/utils.js --content-type application/javascript
